#  Dr Kent G Lau
#  kenty@kenty.com
#  February 2020

#  For testing use only.  No guarantees or warranties provided whatsoever.
#  SPDX-License-Identifier: Apache-2.0

#  Hyperledger Healthcare Special Interest Group (SIG)
#  Patient Consent
#  Clinical Trial Protocol

#  http://github.com/hyperledger-labs/patient-consent
#  1org1peer1channel
#  crypto-config.yml

OrdererOrgs:
  - Name: Orderer
    Domain: patient.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Patient
    Domain: patient.com
    Template:
      Count: 1
    Users:
      Count: 1
