#  Dr Kent G Lau
#  kenty@kenty.com

#  Hyperledger Healthcare Special Interest Group (SIG)
#  Patient Consent
#  Clinical Trial Protocol

#  http://github.com/hyperledger-labs/patient-consent
#  DrKentLau_Fabric
#  LevelDB
#  crypto-config.yaml


OrdererOrgs:

  - Name: Orderer
    Domain: patient.com

    Specs:
      - Hostname: orderer
      - Hostname: orderer2
      - Hostname: orderer3
      - Hostname: orderer4
      - Hostname: orderer5


PeerOrgs:

  - Name: Patient
    Domain: patient.com
    EnableNodeOUs: true

    Template:
      Count: 2

    Users:
      Count: 1

  - Name: Datamanagement
    Domain: datamanagement.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1


  - Name: Oversight
    Domain: oversight.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1


  - Name: Investigator
    Domain: investigator.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1


  - Name: CRO
    Domain: cro.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1


  - Name: Sponsor
    Domain: sponsor.com
    EnableNodeOUs: true
    Template:
      Count: 2
    Users:
      Count: 1
