#  Dr Kent G Lau
#  kenty@kenty.com

#  Hyperledger Healthcare Special Interest Group (SIG)
#  Patient Consent
#  Clinical Trial Protocol

#  http://github.com/hyperledger-labs/patient-consent
#  DrKentLau_Fabric
#  LevelDB
#  configtx.yaml


Organizations:

    - &OrdererOrg

        Name: OrdererOrg

        ID: OrdererMSP

        MSPDir: crypto-config/ordererOrganizations/patient.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Writers:
                Type: Signature
                Rule: "OR('OrdererMSP.member')"
            Admins:
                Type: Signature
                Rule: "OR('OrdererMSP.admin')"


    - &Patient

        Name: PatientMSP

        ID: PatientMSP

        MSPDir: crypto-config/peerOrganizations/patient.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('PatientMSP.admin', 'PatientMSP.peer', 'PatientMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('PatientMSP.admin', 'PatientMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('PatientMSP.admin')"

        AnchorPeers:
            - Host: peer0.patient.com
              Port: 7051


    - &Datamanagement

        Name: DatamanagementMSP

        ID: DatamanagementMSP

        MSPDir: crypto-config/peerOrganizations/datamanagement.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('DatamanagementMSP.admin', 'DatamanagementMSP.peer', 'DatamanagementMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('DatamanagementMSP.admin', 'DatamanagementMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('DatamanagementMSP.admin')"

        AnchorPeers:
            - Host: peer0.datamanagement.com
              Port: 9051


    - &Oversight

        Name: OversightMSP

        ID: OversightMSP

        MSPDir: crypto-config/peerOrganizations/oversight.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OversightMSP.admin', 'OversightMSP.peer', 'OversightMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('OversightMSP.admin', 'OversightMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('OversightMSP.admin')"

        AnchorPeers:
            - Host: peer0.oversight.com
              Port: 11051


    - &Investigator

        Name: InvestigatorMSP

        ID: InvestigatorMSP

        MSPDir: crypto-config/peerOrganizations/investigator.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('InvestigatorMSP.admin', 'InvestigatorMSP.peer', 'InvestigatorMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('InvestigatorMSP.admin', 'InvestigatorMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('InvestigatorMSP.admin')"

        AnchorPeers:
            - Host: peer0.investigator.com
              Port: 13051


    - &CRO

        Name: CROMSP

        ID: CROMSP

        MSPDir: crypto-config/peerOrganizations/cro.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('CROMSP.admin', 'CROMSP.peer', 'CROMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('CROMSP.admin', 'CROMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('CROMSP.admin')"

        AnchorPeers:
            - Host: peer0.cro.com
              Port: 15051


    - &Sponsor

        Name: SponsorMSP

        ID: SponsorMSP

        MSPDir: crypto-config/peerOrganizations/sponsor.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('SponsorMSP.admin', 'SponsorMSP.peer', 'SponsorMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('SponsorMSP.admin', 'SponsorMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('SponsorMSP.admin')"

        AnchorPeers:
            - Host: peer0.sponsor.com
              Port: 17051


Capabilities:

    Channel: &ChannelCapabilities

        V1_3: true

    Orderer: &OrdererCapabilities

        V1_1: true

    Application: &ApplicationCapabilities

        V1_3: true

        V1_2: false

        V1_1: false


Application: &ApplicationDefaults

    Organizations:

    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ApplicationCapabilities


Orderer: &OrdererDefaults

#   OrdererType: solo
    OrdererType: kafka

    Addresses:
#       - orderer.patient.com:7050
        - kafka1.patient.com:9092
        - kafka2.patient.com:9092

    BatchTimeout: 2s

    BatchSize:

        MaxMessageCount: 10

        AbsoluteMaxBytes: 99 MB

        PreferredMaxBytes: 512 KB

    Kafka:

        Brokers:
            - 127.0.0.1:9092

    Organizations:

    Policies:

        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"

        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"

        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"


Channel: &ChannelDefaults

    Policies:

        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"

        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"

        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"

    Capabilities:
        <<: *ChannelCapabilities


Profiles:

    OrdererGenesis:
        <<: *ChannelDefaults

        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
            Capabilities:
                <<: *OrdererCapabilities

        Consortiums:
            ClinicalTrialProtocolConsortium:
                Organizations:
                    - *Patient
                    - *Datamanagement
                    - *Oversight
                    - *Investigator
                    - *CRO
                    - *Sponsor


    PatientChannel:
        Consortium: ClinicalTrialProtocolConsortium
        <<: *ChannelDefaults

        Application:
            <<: *ApplicationDefaults

            Organizations:
                - *Patient
                - *Datamanagement
                - *Oversight

            Capabilities:
                <<: *ApplicationCapabilities


    ConsentChannel:
        Consortium: ClinicalTrialProtocolConsortium
        <<: *ChannelDefaults

        Application:
            <<: *ApplicationDefaults

            Organizations:
                - *Patient
                - *Datamanagement
                - *Oversight
                - *Investigator
                - *CRO
                - *Sponsor

            Capabilities:
                <<: *ApplicationCapabilities


    DataChannel:
        Consortium: ClinicalTrialProtocolConsortium
        <<: *ChannelDefaults

        Application:
            <<: *ApplicationDefaults

            Organizations:
                - *Datamanagement
                - *Oversight
                - *Investigator
                - *CRO
                - *Sponsor

            Capabilities:
                <<: *ApplicationCapabilities
